services:
  nginx:
    image: nginx:1.24.0
    hostname: haha-music
    profiles: ["normal"]
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '${PORT}:80'

  nginx-unexpose:
    image: nginx:1.24.0
    hostname: haha-music
    profiles: ["unexpose"]
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    image: bitnami/php-fpm:8.0
    volumes:
      - ./src:/var/www/html

networks:
  default:
    name: haha-music
    external: true