version: '3'

services:
  haha-nginx:
    image: nginx:1.24.0
    ports:
      - '${PORT}:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  haha-php-fpm:
    image: bitnami/php-fpm:8.0
    volumes:
      - ./src:/var/www/html
