version: '3'

services:
  web:
    image: nginx:1.24.0
    ports:
      - '80:80'
    volumes:
      - ../src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    image: bitnami/php-fpm:8.0
    volumes:
      - ../src:/var/www/html
